#!/bin/bash
#
#Kellaaja järgi tervitades
echo -e "Sisestage soovitud kellaaeg: \c"
read aeg
#Sisestades kellaaeg vahemikus 6-12 kuvab masin teile Hommik peremees
if [ $aeg -ge 6 -a $aeg -lt 12 ];
then
sleep 1
echo "Hommik Peremees!"
#Sisestades kellaaja vahemikus 12-18 siis kuvatakse teile Tere päevast peremees
elif [ $aeg -ge 12 -a $aeg -lt 18 ];
then
sleep 1
echo " Tere päevast peremees"
#Sisestades kellaaja vahemikus 18-22 kuvatakse teile Õhtust Peremees
elif [ $aeg -ge 18 -a $aeg -lt 22 ];
then
sleep 1
echo "Õhtust Peremees"
#Sisestades kellaaja vahemikus 22-24 või vahemikus 0-6 kuvatakse teile Ööd Peremees
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $arg -ge 0 -a $aeg -lt 6 ];
then
sleep 1
echo "Ööd Peremees"
else
sleep 2
echo "Valid error palun proovige uuesti"
fi
#
#skripti lõpp

