#!/bin/bash
#
#Soovite teada saada kas arv on paaris või ei seega peate sisestama vajalikud arvud
echo -n "Tervist! Sisestage suvaline täisarvuke: "
read arv
if [ $(($arv%2)) -eq 0 ];
#Kui arv on paaris siis kuvab masin et see on paaris
then
echo "$arv on paarisarv"
else
echo "$arv on paarituarv"
fi
#
#skripti lõpp
