#!/bin/bash
#
#Kas sisestatud arv on ikka algarv????
#uURIME järgi
echo -e "Tervist! Sisestage üks arvumasin: "
sleep 1
read arv
#kui
if [ $arv -eq 0 -o $arv -eq 1 ];
then
 echo "$arv - ei ole algarv"
else
  jagaja=2
  jaa=$((arv % $jagaja))
 while [ $jaak -ne 0 ]
 do
   jagaja=$(($jagaja + 1))
   jaak=$(($arv % $jagaja))
done
if [ $arv -eq $jagaja ];
then
echo "$arv - on algarv"
else
echo "$arv - ei ole algarv"
fi
fi
#
#lõpp
