#!/bin/bash
#Kombineerimine 
#joink 7 gpeatükk 6 lehekülg 21
echo "Mitu rida oleks teie soovitud?"
read r
var1=$r
var2=$r
for (( j = 1; j <= $r; j++))
do
echo -n $j". "
for (( i = 1; i <= $r-j; i++ ))
do
echo -n "o"
done
for (( k = 1; k <=j; K++))
do
echo -n "*"
done
echo ""
done
#lõpp peatus

